config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/articles/new', to: 'articles#new', as: :article_new
  post '/articles', to: 'articles#create'
  get '/articles/:id/edit', to: 'articles#edit', as: :article_edit
  patch 'articles/:id', to: 'articles#update'
  get '/articles/:id', to: 'articles#show', as: :article
  get '/articles', to: 'articles#index'
  delete '/articles/:id', to: 'articles#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :find_article, only: [:show, :edit, :destroy, :update]
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Task.new(article_params)
    @article.save
    redirect_to article_path(@task)
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@task)
  end

  def destroy
    @article.destory
  end

  def edit; end

  def show; end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <ul>
    <% @article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class= "container">
<%= form_for(@article) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group mt-1">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>
  <%= link_to 'back', articles_path %>
</div>

app/views/articles/edit.html.erb
<%= render 'form'%>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
  <% @articles.each do |article|%>
    <div class="col-sm-8 col-sm-offset-2">
      <h2><%= link_to article.title, article_path(article) %></h2>
      <p><%= article.content %>
    </div>
  <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<%= render 'form'%>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.content %></p>


  <%= link_to 'back', articles_path %>
  <%= link_to 'edit', article_edit_path(@article) %>
  <%= link_to 'delete', article_path(@article), method: :delete, data: { confirm: "Are you sure to deliete #{@article.title}? "} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>